import { AgentInput, AgentOutput, ArtifactFile, SubAgent } from '../types';

function deployPlanMarkdown(): string {
  return [
    '# Agentic Deploy Plan',
    '',
    'This plan outlines deployment to Vercel (app) and Supabase (DB). Two modes available: **automated** (via script) or **manual** (step-by-step).',
    '',
    '## Automated Mode (Recommended)',
    '',
    '### Prerequisites',
    '- Vercel account with CLI installed (`npm i -g vercel`)',
    '- Vercel token: `vercel login` or create at https://vercel.com/account/tokens',
    '- Supabase: access token + organization ID (for automation) or hosted project ready',
    '- Stripe keys (test or production)',
    '',
    '### Steps',
    '1. Set environment variables in your shell or `.env.local`:',
    '   ```bash',
    '   export VERCEL_TOKEN=your_token',
    '   export VERCEL_ORG_ID=team_xxx  # optional, for team projects',
    '   export NEXT_PUBLIC_SUPABASE_URL=https://xxx.supabase.co',
    '   export NEXT_PUBLIC_SUPABASE_ANON_KEY=xxx',
    '   export SUPABASE_SERVICE_ROLE_KEY=xxx',
    '   export NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_xxx',
    '   export STRIPE_SECRET_KEY=sk_test_xxx',
    '   export STRIPE_WEBHOOK_SECRET=whsec_xxx',
    '   ```',
    '',
    '2. Initialize Supabase (optional automation):',
    '   ```bash',
    '   export SUPABASE_ACCESS_TOKEN=sbp_xxx',
    '   export SUPABASE_ORG_ID=org_xxx',
    '   export SUPABASE_DB_PASSWORD=StrongPassword123',
    '   npm run agentic:init-supabase',
    '   ```',
    '   Capture the generated Supabase URL/keys and export them for deploy script.',
    '',
    '3. Run the deployment script:',
    '   ```bash',
    '   npm run agentic:deploy',
    '   ```',
    '',
    '4. Scripts will:',
    '   - Create or link Supabase project (optional) and output keys',
    '   - Create or link Vercel project',
    '   - Upload environment variables',
    '   - Trigger preview deployment',
    '   - Return preview URL',
    '',
    '5. Validate the preview deployment',
    '6. Promote to production via Vercel dashboard',
    '',
    '## Manual Mode',
    '',
    '### 1) Vercel Project',
    '1. Create a new project in Vercel and link this repo',
    '2. Set Environment Variables (see env list in ENV_TEMPLATE)',
    '3. Framework Preset: Next.js',
    '4. Build Command: `next build`  Output: `.next`',
    '',
    '### 2) Supabase (Hosted)',
    '1. Create a new Supabase project',
    '2. Copy the URL and anon/service keys to Vercel envs',
    '3. Apply migrations from `supabase/migrations/` via SQL Editor or `supabase db push`',
    '',
    '### 3) Stripe Webhooks',
    '1. In Stripe Dashboard, add endpoint: `https://your-app.vercel.app/api/webhooks/stripe`',
    '2. Select events: `checkout.session.completed`, `customer.subscription.*`, `invoice.payment_failed`',
    '3. Copy webhook secret and set `STRIPE_WEBHOOK_SECRET` in Vercel',
    '',
    '### 4) Deploy',
    '1. Trigger deploy from Vercel dashboard or `vercel --prod`',
    '2. Validate auth, DB access, and payments flow',
    '',
    '## Environment Variables',
    'See `agentic/deploy/ENV_TEMPLATE` for full list with descriptions.',
  ].join('\n');
}

function envTemplate(): string {
  return [
    '# Environment Variables Template',
    '# Copy these into Vercel project settings or set in your shell for automated deploy',
    '',
    '# Required: Vercel (for automated deploy)',
    'VERCEL_TOKEN=          # Get from https://vercel.com/account/tokens',
    'VERCEL_ORG_ID=         # Optional: team_xxx for team projects',
    'VERCEL_PROJECT_ID=     # Optional: reuse existing project',
    'VERCEL_PROJECT_NAME=   # Optional: custom project name (default: agentic-saas)',
    '',
    '# Optional: Supabase automation',
    'SUPABASE_ACCESS_TOKEN=         # From https://supabase.com/dashboard/account/tokens',
    'SUPABASE_ORG_ID=               # Supabase organization ID',
    'SUPABASE_PROJECT_NAME=         # Defaults to agentic-saas-db',
    'SUPABASE_REGION=               # Defaults to us-east-1',
    'SUPABASE_PLAN=                 # Defaults to free',
    'SUPABASE_DB_PASSWORD=         # Strong password for new project',
    'SUPABASE_PROJECT_REF=         # Optional: reuse existing project',
    'SUPABASE_APPLY_MIGRATIONS=    # Set to "true" to run supabase db push',
    '',
    '# Required: Supabase',
    'NEXT_PUBLIC_SUPABASE_URL=         # https://xxx.supabase.co',
    'NEXT_PUBLIC_SUPABASE_ANON_KEY=    # Public anon key',
    'SUPABASE_SERVICE_ROLE_KEY=        # Server-side only (secret)',
    '',
    '# Required: Stripe',
    'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=   # pk_test_xxx or pk_live_xxx',
    'STRIPE_SECRET_KEY=                    # sk_test_xxx or sk_live_xxx (secret)',
    'STRIPE_WEBHOOK_SECRET=                # whsec_xxx from Stripe dashboard (secret)',
    '',
    '# Optional: Stripe Price IDs (for pricing page)',
    'NEXT_PUBLIC_STRIPE_PRICE_PRO_MONTHLY=      # price_xxx',
    'NEXT_PUBLIC_STRIPE_PRICE_PRO_YEARLY=',
    'NEXT_PUBLIC_STRIPE_PRICE_ENTERPRISE_MONTHLY=',
    'NEXT_PUBLIC_STRIPE_PRICE_ENTERPRISE_YEARLY=',
    '',
    '# Optional: App Branding',
    'NEXT_PUBLIC_APP_NAME=              # Your SaaS Name',
    'NEXT_PUBLIC_SITE_URL=              # https://yourdomain.com',
  ].join('\n');
}

function deployChecklist(): string {
  return [
    '# Deployment Checklist',
    '',
    '## Pre-Deployment',
    '- [ ] Create Supabase project (hosted) at https://supabase.com',
    '- [ ] Copy Supabase URL and keys',
    '- [ ] Create Stripe account (or use existing)',
    '- [ ] Copy Stripe publishable and secret keys',
    '- [ ] Install Vercel CLI: `npm i -g vercel`',
    '- [ ] Get Vercel token: `vercel login` or https://vercel.com/account/tokens',
    '',
    '## Automated Deploy (Recommended)',
    '- [ ] Set all required env vars (see ENV_TEMPLATE)',
    '- [ ] (Optional) Run `npm run agentic:init-supabase` to create hosted project',
    '- [ ] Run `npm run agentic:deploy`',
    '- [ ] Note the preview URL from output',
    '- [ ] Validate preview deployment',
    '',
    '## Post-Deployment',
    '- [ ] Apply Supabase migrations via SQL Editor or CI',
    '- [ ] Configure Stripe webhook endpoint: `https://your-app.vercel.app/api/webhooks/stripe`',
    '- [ ] Select webhook events: `checkout.session.completed`, `customer.subscription.*`, `invoice.payment_failed`',
    '- [ ] Copy webhook secret and update `STRIPE_WEBHOOK_SECRET` in Vercel',
    '- [ ] Test auth flow (sign up, login)',
    '- [ ] Test CRUD operations',
    '- [ ] Test payment flow (use Stripe test cards)',
    '- [ ] Promote to production in Vercel dashboard',
    '',
    '## Production Checklist',
    '- [ ] Switch to Stripe live keys',
    '- [ ] Update webhook endpoint with live webhook secret',
    '- [ ] Configure custom domain in Vercel',
    '- [ ] Enable SSL/HTTPS',
    '- [ ] Set up monitoring and alerts',
  ].join('\n');
}

export class DeploymentAgent implements SubAgent {
  id = 'deployment-agent';

  async run(_input: AgentInput): Promise<AgentOutput> {
    try {
      const artifacts: ArtifactFile[] = [
        { path: 'agentic/deploy/DEPLOY_PLAN.md', content: deployPlanMarkdown() },
        { path: 'agentic/deploy/ENV_TEMPLATE', content: envTemplate() },
        { path: 'agentic/deploy/CHECKLIST.md', content: deployChecklist() },
      ];
      const notes = [
        'DeploymentAgent: generated deploy plan artifacts',
        'No external systems were changed; follow DEPLOY_PLAN.md manually or wire into CI.',
      ];
      return { status: 'ok', artifacts, logs: notes };
    } catch (e: any) {
      return { status: 'error', artifacts: [], error: e?.message ?? 'Unknown error' };
    }
  }
}

export default DeploymentAgent;
